[Interface]
PrivateKey = MJhc72QQEHpJmhL+fk3Np0WYScp6NlG3yCytHPDx00A=
Address = 10.8.0.2/32
DNS = 8.8.8.8
MTU = 1360

[Peer]
PublicKey = /2FG41n+u3UnRkY96OMDAMTgJ9ykgxSOC/FJ53yAEko=
Endpoint = 43.157.204.11:51820
AllowedIPs = 10.8.0.0/24
PersistentKeepalive = 10
